language: python
python:
  - 3.3
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install sphinx
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:
  - nosetests
  - cd docs
  - make html
