arch: 
    - ppc64le
    - amd64

dist: trusty
language: python
matrix:
  include:
     - python: "3.5"
      env: TEST_SUITE=suite_3_5
    - python: "3.6"
      env: TEST_SUITE=suite_3_6
    - python: "3.7"
      dist: xenial # Required for Python 3.7
      sudo: true   # travis-ci/travis-ci#9069
      env: TEST_SUITE=suite_3_7
      
      
install:
  - if [[ $TEST_SUITE == suite_3_6 ]]; then
        pip install sphinx;
    fi;
  - pip install coverage
  - pip install -r requirements.txt
  - python setup.py install
script:
  - nosetests --with-coverage  --cover-erase --cover-package=bibtexparser
  - if [[ $TEST_SUITE == suite_3_6 ]]; then
        cd docs;
        make html;
    fi;

after_success:
  - pip install coveralls
  - coveralls
