language: python
python:
  - 3.2
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install: PLEASE CHANGE ME
# command to run tests, e.g. python setup.py test
script: nosetests
